arch/ceva: Add missing comma
This patch fixes following error, fond by cppcheck.

up_hardfault.c:103:0: error: failed to expand 'hfdumpreg4',
 Wrong number of parameters for macro 'hfdumpreg4'

Change-Id: Ie387ac20878855efa4c034e7af125d7502798acd
Signed-off-by: Masanari Iida <standby24x7@gmail.com>